openapi: 3.1.0
info:
  title: ValtioData plugin API
  version: "0.1"
  description: |
    Budjettihaukka-GPT:n käyttämä rajapinta Suomen valtion budjettitalouden tapahtumien hakuun (huhtikuu 2022 – huhtikuu 2025).
servers:
  - url: https://budjettihaukka-gpt-272775413944.europe-north1.run.app

paths:
  /budjettidata:
    get:
      operationId: getBudgetData
      summary: Proxy Tutkihallintoa-rajapintaan
      parameters:
        - name: yearFrom
          in: query
          schema:
            type: integer
        - name: yearTo
          in: query
          schema:
            type: integer
        - name: monthFrom
          in: query
          schema:
            type: integer
        - name: monthTo
          in: query
          schema:
            type: integer
        - name: momentti
          in: query
          schema:
            type: string
        - name: hallinnonala
          in: query
          schema:
            type: integer
        - name: tilivirasto
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Lista valtion budjettitalouden tapahtumista
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Vuosi:
                      type: integer
                    Kk:
                      type: integer
                    Hallinnonala:
                      type: string
                    Momentti_TunnusP:
                      type: string
                    Momentti_sNimi:
                      type: string
                    Voimassaoleva_talousarvio:
                      type: number
                    Nettokertymä:
                      type: number
