openapi: 3.0.0
info:
  title: Budjettihaukka GPT API
  description: Hakee ja muuntaa valtiontalouden dataa Tutkihallintoa.fi-palvelusta ChatGPT:n käyttöön.
  version: "v1.0.1" # Voit päivittää versionumeroa tarvittaessa
servers:
  - url: https://budjettihaukka-gpt-272775413944.europe-north1.run.app # SINUN CLOUD RUN FUNKTION URL
paths:
  /: # Oletetaan, että funktiosi vastaa juuripolkuun.
    get:
      summary: Hae valtiontalouden tapahtumia
      description: Noutaa dataa Tutkihallintoa.fi API:sta annettujen parametrien perusteella ja palauttaa sen JSON-muodossa.
      operationId: budjettidataHandler # TAI esim. haeValtiontalousDataa. Selkeä ja uniikki.
      parameters:
        # Tässä listataan kaikki parametrit, joita funktio voi ottaa vastaan
        # Nämä vastaavat ALLOWED_PARAMS-listaa Python-koodissa.
        - name: momentti
          in: query
          required: false
          description: Talousarvion momentin tunnus.
          schema:
            type: string
        - name: luku
          in: query
          required: false
          description: Talousarvion luvun tunnus.
          schema:
            type: string
        - name: paaluokka
          in: query
          required: false
          description: Talousarvion pääluokan tunnus.
          schema:
            type: string
        - name: takptili # Muista lisätä kaikki ALLOWED_PARAMS tänne
          in: query
          required: false
          description: Tarkemman kirjanpidon tilin tunnus.
          schema:
            type: string
        - name: tililaji
          in: query
          required: false
          description: Tililajin tunnus.
          schema:
            type: string
        # --- JATKA MUIDEN ALLOWED_PARAMS PARAMETRIEN LISÄÄMISTÄ VASTAAVASTI ---
        # Esimerkiksi: tiliryhma, ylatiliryhma, tililuokka, lkptili
        - name: hallinnonala
          in: query
          required: false
          description: Hallinnonalan koodi.
          schema:
            type: string
        - name: tilivirasto
          in: query
          required: false
          description: Tiliviraston tunnus.
          schema:
            type: string
        - name: monthFrom
          in: query
          required: false
          description: Aloituskuukausi (1-12).
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 12
        - name: monthTo
          in: query
          required: false
          description: Lopetuskuukausi (1-12).
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 12
        - name: yearFrom
          in: query
          required: false
          description: Aloitusvuosi (esim. 2023).
          schema:
            type: integer
            format: int32
        - name: yearTo
          in: query
          required: false
          description: Lopetusvuosi (esim. 2024).
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Onnistunut haku. Palauttaa listan tapahtumia JSON-muodossa.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  # Tähän voi tarkentaa objektin rakennetta (properties),
                  # jos tiedät tarkalleen CSV-sarakkeiden otsikot.
        # ... (Muut vastauskoodit, kuten 4xx, 5xx, kuten aiemmassa esimerkissä) ...
components:
  schemas:
    ErrorResponse: # Esimerkki virhevastaukselle
      type: object
      properties:
        error:
          type: string
        details:
          type: string
