openapi: 3.1.0
info:
  title: ValtioData API Budjettidatalle (CSV)
  version: "0.5.0" # Uusi versionumero suomenkielisillä kuvauksilla
  description: |
    Rajapinta Suomen valtion budjettitalouden tietojen hakemiseen. 
    Palauttaa dataa CSV-muodossa. Tiedot ovat saatavilla aikaväliltä huhtikuu 2022 – huhtikuu 2025.
    Tämä YAML-tiedosto on tallennettu UTF-8-muodossa.

servers:
  - url: https://budjettihaukka-gpt-272775413944.europe-north1.run.app
    description: Tuotantopalvelin Budjettihaukka-GPT:n rajapinnalle.

paths:
  /budjettidata:
    get:
      operationId: getBudgetDataCsvFinnishDesc
      summary: Hae valtion budjettidataa CSV-muodossa.
      description: |
        Noutaa listan Suomen valtion budjettitalouden tapahtumista määritellyillä kriteereillä.
        Vastaus on CSV-muotoinen merkkijono. Ensimmäinen rivi on otsikkorivi.
        Dataa on saatavilla aikaväliltä huhtikuu 2022 – huhtikuu 2025.
        Käytä parametreja haun rajaamiseen.
      parameters:
        - name: yearFrom
          in: query
          description: "Aloitusvuosi haulle. Pakollinen. Sallittu aikaväli: 2022-2025."
          required: true
          schema:
            type: integer
            minimum: 2022
            maximum: 2025
          example: 2023
        - name: yearTo
          in: query
          description: "Päättymisvuosi haulle. Pakollinen. Sallittu aikaväli: 2022-2025."
          required: true
          schema:
            type: integer
            minimum: 2022
            maximum: 2025
          example: 2023
        - name: monthFrom
          in: query
          description: "Aloituskuukausi (1-12). Jos 'yearFrom' on 2022, 'monthFrom' täytyy olla >= 4 (huhtikuu)."
          schema:
            type: integer
            minimum: 1
            maximum: 12
          example: 4
        - name: monthTo
          in: query
          description: "Päättymiskuukausi (1-12). Jos 'yearTo' on 2025, 'monthTo' täytyy olla <= 4 (huhtikuu)."
          schema:
            type: integer
            minimum: 1
            maximum: 12
          example: 12
        - name: momentti
          in: query
          description: "Talousarvion momentin tunnus (esim. '28.50.01') tai osa momentin nimestä (esim. 'Yleinen tuomioistuinlaitos', 'Työttömyysetuudet'). Haku on yleensä kirjainkoosta riippumaton."
          schema:
            type: string
          example: "Työttömyysetuudet" # Esimerkki voi sisältää suomalaisia merkkejä
        - name: hallinnonala
          in: query
          description: "Hallinnonalan numeerinen tunnus (esim. '12' Oikeusministeriölle) tai nimi. Tarkista tuetut arvot."
          schema:
            type: string 
          example: "12"
        - name: tilivirasto
          in: query
          description: "Tiliviraston numeerinen tunnus (esim. '286' Tuomioistuinlaitokselle) tai nimi. Tarkempi kuin hallinnonala."
          schema:
            type: string
          example: "286"
      responses:
        "200":
          description: |
            Onnistunut vastaus CSV-muodossa. Ensimmäinen rivi sisältää sarakeotsikot.
            Pilkku (,) toimii erottimena. Kentät, jotka sisältävät erikoismerkkejä (pilkku, rivinvaihto, lainausmerkki), 
            on ympäröity tuplalainausmerkeillä RFC 4180 -standardin mukaisesti.
            Varsinainen API-vastaus voi sisältää suomalaisia merkkejä (ä, ö, å) UTF-8 enkoodattuna.
          content:
            text/csv: 
              schema:
                type: string
                # Tämä YAML-tiedoston sisäinen esimerkki käyttää ASCII-vastineita sarakenimissä ja esimerkkisisällössä
                # YAML-parserin toiminnan varmistamiseksi importointivaiheessa.
                # Todellinen API-vastaus voi ja sen pitäisi sisältää oikeat suomalaiset merkit (esim. "Nettokertymä", "Valtion taidemuseo (arviomääräraha)").
                example: |
                  Vuosi,Kk,Hallinnonala,Momentti_TunnusP,Momentti_sNimi,Voimassaoleva_talousarvio,Nettokertyma
                  2023,6,"Opetus ja kulttuuriministerio","29.40.51","Valtion taidemuseo (arviomaararaha)",100000.00,50000.00
                  2024,1,"Sosiaali ja terveysministerio","33.10.01","Tyottomyysturvan menot (siirtomaararaha)",2500000000.00,200000000.00
        "400":
          description: "Virheellinen pyyntö. Yksi tai useampi parametri on virheellinen tai puuttuu."
          content:
            text/plain; charset=utf-8: # Virheilmoitukset tekstinä, UTF-8 mukainen
              schema:
                type: string
                example: "Virheellinen parametri 'yearFrom'. Arvon tulee olla välillä 2022-2025."
        "500":
          description: "Sisäinen palvelinvirhe. Palvelimella tapahtui odottamaton virhe."
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                example: "Sisäinen palvelinvirhe. Yritä myöhemmin uudelleen."
