openapi: 3.1.0
info:
  title: Simple Budget API (CSV)
  version: "0.6.0" # Version for this simplified approach
  description: A simple API to fetch Finnish state budget data in CSV format. All descriptions in this schema are ASCII for maximum import compatibility.

servers:
  - url: https://budjettihaukka-gpt-272775413944.europe-north1.run.app
    description: API Server URL

paths:
  /budjettidata:
    get:
      operationId: getSimpleBudgetDataCsv
      summary: Get budget data as CSV.
      description: Fetches budget data. Response is CSV. Data from April 2022 - April 2025.
      parameters:
        - name: yearFrom
          in: query
          description: "Start year. Required. Range: 2022-2025."
          required: true
          schema:
            type: integer
            minimum: 2022
            maximum: 2025
          example: 2023
        - name: yearTo
          in: query
          description: "End year. Required. Range: 2022-2025."
          required: true
          schema:
            type: integer
            minimum: 2022
            maximum: 2025
          example: 2023
        - name: monthFrom
          in: query
          description: "Start month (1-12). If yearFrom is 2022, must be >= 4."
          schema:
            type: integer
            minimum: 1
            maximum: 12
          example: 4
        - name: monthTo
          in: query
          description: "End month (1-12). If yearTo is 2025, must be <= 4."
          schema:
            type: integer
            minimum: 1
            maximum: 12
          example: 12
        - name: momentti
          in: query
          description: "Budget item ID or part of name (e.g., '28.50.01')."
          schema:
            type: string
          example: "28.50.01"
        - name: hallinnonala
          in: query
          description: "Administrative branch ID or name (e.g., '12')."
          schema:
            type: string
          example: "12"
        - name: tilivirasto
          in: query
          description: "Accounting office ID or name (e.g., '286')."
          schema:
            type: string
          example: "286"
      responses:
        "200":
          description: Successful CSV response. First row is header. Comma delimited.
          content:
            text/csv:
              schema:
                type: string
                # This example string within the YAML is pure ASCII.
                # The actual API response can and should still contain UTF-8 Finnish characters.
                example: |
                  Vuosi,Kk,Hallinnonala,Momentti_TunnusP,Momentti_sNimi,Voimassaoleva_talousarvio,Nettokertyma
                  2023,6,"Opetus ja kulttuuriministerio","29.40.51","Valtion taidemuseo (arviomaararaha)",100000.00,50000.00
                  2024,1,"Sosiaali ja terveysministerio","33.10.01","Tyottomyysturvan menot (siirtomaararaha)",2500000000.00,200000000.00
        # For simplicity in this import attempt, explicit error responses (400, 500 etc.) are omitted.
        # They can be added back once basic import is successful.
